---
# role: fail2ban
# file: tasks/filter.yml

- name: "FAIL2BAN | Manage custom filter"
  become: true
  become_user: root
  community.general.ini_file:
    path: "/etc/fail2ban/filter.d/{{ __fail2ban_option.0.name }}.local"
    section: "{{ __fail2ban_option.1.section }}"
    option: "{{ __fail2ban_option.1.option }}"
    value: "{{ __fail2ban_option.1.value | default(omit) }}"
    state: "{{ __fail2ban_option.1.state | default('present') }}"
    owner: root
    group: root
    mode: '0640'
    backup: true
  loop: "{{ fail2ban_filters | subelements('options') }}"
  loop_control:
    loop_var: __fail2ban_option
    label: "{{ __fail2ban_option.0.name }}: {{ __fail2ban_option.1.section }}.{{ __fail2ban_option.1.option }}"
  notify: restart service
