---
# role: fail2ban
# file: tasks/main.yml

- name: "FAIL2BAN | Validate configuration file names"
  ansible.builtin.assert:
    that:
      - __fail2ban_object.name is match('^[^/\\\\\s]+\Z')
    fail_msg: Configuration names must be nonempty and contain no path separators or whitespace.
    quiet: true
  loop: "{{ fail2ban_actions + fail2ban_filters + fail2ban_jails }}"
  loop_control:
    loop_var: __fail2ban_object
    label: "{{ __fail2ban_object.name }}"

- name: "FAIL2BAN | Install fail2ban"
  become: true
  become_user: root
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: "FAIL2BAN | Generate fail2ban configuration"
  become: true
  become_user: root
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: '0640'
    backup: true
  notify: restart service

- name: "FAIL2BAN | Manage default jail options"
  become: true
  become_user: root
  community.general.ini_file:
    path: /etc/fail2ban/jail.local
    section: "{{ __fail2ban_option.section }}"
    option: "{{ __fail2ban_option.option }}"
    value: "{{ __fail2ban_option.value | default(omit) }}"
    state: "{{ __fail2ban_option.state | default('present') }}"
    owner: root
    group: root
    mode: '0640'
    backup: true
  loop: "{{ fail2ban_jail_local }}"
  loop_control:
    loop_var: __fail2ban_option
    label: "{{ __fail2ban_option.section }}.{{ __fail2ban_option.option }}"
  notify: restart service

- name: "FAIL2BAN | Configure custom actions"
  ansible.builtin.import_tasks: action.yml

- name: "FAIL2BAN | Configure custom filters"
  ansible.builtin.import_tasks: filter.yml

- name: "FAIL2BAN | Configure custom jails"
  ansible.builtin.import_tasks: jail.yml

- name: "FAIL2BAN | Start fail2ban service"
  become: true
  become_user: root
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
