---
# role: fail2ban
# file: handlers/main.yml

- name: "FAIL2BAN | Restart fail2ban"
  become: true
  become_user: root
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  listen: restart service
