---
# role: fail2ban
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        fail2ban_loglevel: "NOTICE"
        fail2ban_jail_local:
          - section: "DEFAULT"
            option: "bantime"
            state: "absent"
          - section: "DEFAULT"
            option: "findtime"
            value: 60
          - section: "DEFAULT"
            option: "maxretry"
            value: 1
          - section: "sshd"
            option: "enabled"
            value: false
        fail2ban_actions:
          - name: "molecule"
            options:
              - section: "Definition"
                option: "actionban"
                state: "absent"
              - section: "Definition"
                option: "actioncheck"
                value: "true"
        fail2ban_filters:
          - name: "molecule"
            options:
              - section: "Definition"
                option: "ignoreregex"
                state: "absent"
              - section: "Definition"
                option: "failregex"
                value: "^\\s*<HOST> authentication failed$$"
        fail2ban_jails:
          - name: "molecule"
            options:
              - section: "molecule"
                option: "findtime"
                state: "absent"
              - section: "molecule"
                option: "enabled"
                value: true
              - section: "molecule"
                option: "backend"
                value: "polling"
              - section: "molecule"
                option: "filter"
                value: "molecule"
              - section: "molecule"
                option: "action"
                value: "molecule"
              - section: "molecule"
                option: "logpath"
                value: "/var/log/fail2ban-molecule.log"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-fail2ban"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "debian-latest-fail2ban"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-fail2ban"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-fail2ban"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-fail2ban"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-fail2ban"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
