---
# role: fail2ban
# file: molecule/resources/playbooks/converge.yml

- name: "Molecule | converge | fail2ban"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
